### ISSUE TITLE
Several errors when calling loss.backward with AnalyticFreeFB

### ISSUE THREAD

**Issue by antimora** [mpariente/AsSteroid#18]
Tried to use your sample code, and it works stand alone but when training with it, I get "not on right device" errors and some strange error after fixing it.

Here is the code snippet I included: 

```python
encoder = Encoder(AnalyticFreeFB(n_filters=512,
                                 kernel_size=256,
                                 stride=128))
```

I get this error:

```
  File "/workspaces/speechml/AsSteroid/asteroid/filterbanks/enc_dec.py", line 131, in forward
    return F.conv1d(waveform, filters, stride=self.stride)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

```
After fixing this error with this patched code:

```python

def forward(self, waveform):
    """ Convolve 1D torch.Tensor with filterbank."""
    filters = self.get_filters()

    filters = filters.to(waveform.device)  # <- Patched code 

    return F.conv1d(waveform, filters, stride=self.stride)

```

I still get this error when training with GPU device:

```
Traceback (most recent call last):
  File "/workspaces/speech/scripts/train.py", line 66, in train
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: expected device cpu but got device cuda:0
```

But if I train to CPU only, I get this error:
```
  File "/workspaces/speech/scripts/train.py", line 66, in train
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, 
but the buffers have already been freed. Specify retain_graph=True 
when calling backward the first time.
```

Any hints why this is?

**Comment by mpariente** [comment]
Thanks a lot for reporting that, [this commit](https://github.com/mpariente/AsSteroid/commit/d5c56e66aff5f577ce90ed353c7028694dfdb1f6) will solve the device issues. 

The last error you report doesn't seem to be related.. Can you make it happen again? If yes, can you give me a code snippet to reproduce please? 

This toy example works for both GPU and CPU usage.
```
import torch
from asteroid.filterbanks import Encoder, AnalyticFreeFB, FreeFB

USE_CUDA = True

inp = torch.randn(2, 1, 32000)
enc = Encoder(AnalyticFreeFB(n_filters=512,
                             kernel_size=64,
                             stride=32))
if USE_CUDA:
    inp = inp.cuda()
    enc = enc.cuda()

out = enc(inp)
real_out = torch.randn(*out.shape).to(out.device)
loss = torch.mean((out - real_out).pow(2))
loss.backward()
```

**Comment by popcornell** [comment]
I have been able to reproduce the error:  `RuntimeError: Trying to backward through the graph a second time, 
but the buffers have already been freed. Specify retain_graph=True 
when calling backward the first time.`
But after your latest commit it disappeared and the AnalyticFreeFB works fine for me.

**Comment by antimora** [comment]
Thank you! I can confirm this issue has been fixed for me.

**Comment by mpariente** [comment]
Great, I'll close the issue, feel free to re-open if needed.
